apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/cpapasta-tenant/devfile-sample/devfile-sample@sha256:ecde8a421baf74e2dd84ce4e85ea9fdb0d96f01e5829be166eb218b807ee7dc5
        name: my-nodejs
        resources: {}
status: {}
